// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Minecraft_5._0.Data;

namespace Minecraft_5._0.Migrations
{
    [DbContext(typeof(AppDBContent))]
    [Migration("20220620130359_Initial_3")]
    partial class Initial_3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Minecraft_5._0.Data.Models.photo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("imagesrc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("thingid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("thingid");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("Minecraft_5._0.Data.Models.thing", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("date")
                        .HasColumnType("datetime2");

                    b.Property<string>("discription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("photoBillsrc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("quantity")
                        .HasColumnType("int");

                    b.Property<int>("userid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("userid");

                    b.ToTable("Things");
                });

            modelBuilder.Entity("Minecraft_5._0.Data.Models.user", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Firstname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Minecraft_5._0.Data.Models.photo", b =>
                {
                    b.HasOne("Minecraft_5._0.Data.Models.thing", "thing")
                        .WithMany("photos")
                        .HasForeignKey("thingid");

                    b.Navigation("thing");
                });

            modelBuilder.Entity("Minecraft_5._0.Data.Models.thing", b =>
                {
                    b.HasOne("Minecraft_5._0.Data.Models.user", "user")
                        .WithMany("things")
                        .HasForeignKey("userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("Minecraft_5._0.Data.Models.thing", b =>
                {
                    b.Navigation("photos");
                });

            modelBuilder.Entity("Minecraft_5._0.Data.Models.user", b =>
                {
                    b.Navigation("things");
                });
#pragma warning restore 612, 618
        }
    }
}
